#!/usr/bin/python
# encoding:utf-8

import Xiami
import V2EX

print "smartCheckin start ... \n"
##Xiami Checkin
xiami = Xiami.Xiami("twilight.zheng@gmail.com", "zllz8374721")
xiami.run()

##V2EX Checkin
v2ex = V2EX.V2EX("jinyue524", "zllz8374721")
v2ex.run()

print "smartCheckin done!"
