#!/usr/bin/python
# encoding:utf-8

import Xiami
import V2EX
import Load

print "smartCheckin start ... \n"

##Xiami Checkin
account, success = Load.get("Xiami.json")
if success:
    for email in account.keys():
        xiami = Xiami.Xiami(email, account[email])
        xiami.run()

##V2EX Checkin
account, success = Load.get("V2EX.json")
if success:
    for username in account.keys():
        v2ex = V2EX.V2EX(username, account[username])
        v2ex.run()

print "smartCheckin done!"
